// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// edfReader
List edfReader(std::string fileName);
RcppExport SEXP eyelinkReader_edfReader(SEXP fileNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type fileName(fileNameSEXP);
    __result = Rcpp::wrap(edfReader(fileName));
    return __result;
END_RCPP
}
